### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by Joccob**
Hi, my name is Joccob, I dont know if this is a proper way to get the reprint permission. But since you are really busy and this might be the easiest way to communicate with you without wasting your time.
I really like your Galacticraft mod. I wonder if I can reprint this mod on MCBBS which is one of the most famous Chinese minecraft forum. I will introduce this mod to more Chinese so that they can enjoy your mod as well. I will NOT take any credits of the mod and all the link will direct to your official website. I do need your permission to do this, so are you ok with that?

### CODE REVIEW

**Comment by radfast** [comment]
Hi Joccob.  That sounds good, you can have permission BUT please post here a link to the thread you make on MCBBS.

3 main points to get across to your Chinese players:
* Galacticraft is regularly updated and players are recommended always to use the 'Latest' version
* There is full and up-to-date documentation (in English) on the Wiki
* There is a support forum (in English) at http://forum.micdoodle8.com/index.php?forums/support.5/

Also ... if somebody some time wants to undertake the (huge) project of translating the Wiki into Chinese that would also be awesome.  It is possible to add Chinese language versions of any page, the same way as how currently there are some pages in Russian language.

**Comment by Joccob** [comment]
Here is the linke to my thread on MCBBS : http://www.mcbbs.net/thread-435616-1-1.html
And as for the Official Wiki translation project...umm, i dont know, i might give it a try. But you are right, it is a huge project.

**Comment by radfast** [comment]
Thank you for the link, we will be pleased to have more Chinese-speaking players.

Translating the Wiki, the secret of success is to translate only 1 or 2 pages each day ... that way it's manageable.  This is probably the most important: http://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Getting_Started_Guide

**Comment by Joccob** [comment]
Still a little bit confusing about the translation project. I'm not sure where to update. I mean there are two ways.

First, I create a new page called "Galacticraft Chinese wiki" on your official website(I dont know how and also I didn't find the Russian wiki page on the website, so no sure about what is "the same way"). 

And the other way is to do all the translation on www.mcmod.cn ---- which is a large Chinese mods wiki. And I will give the specific page link of Galacticraft to you. Personally I prefer this way.

But its up to you. So what do you think?

**Comment by radfast** [comment]
On the Wiki pages there are national flags in the top right corner if another language is available.  

Once you get into the other language then everything is there in that language.

This is the Russian.  http://wiki.micdoodle8.com/wiki/%D0%9E%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/Galacticraft_%D0%B4%D0%BB%D1%8F_%D0%BD%D0%B0%D1%87%D0%B8%D0%BD%D0%B0%D1%8E%D1%89%D0%B8%D1%85
Unfortunately about 75% of the Russian is uncompleted, and it's not very up to date.  It is probably a job for more than one person...

**Pull request merged**
