### PR TITLE
Translated 99.9% of English lines

### PR DESCRIPTION
**Pull request by Romsik788**
I translated almost everything from English except one line. In the end, I marked ##NEEDS TRANSLATE##

### CODE REVIEW

**Comment by radfast** [comment]
Thank you again.

The "Slimeling Inventory" looks OK in Google translate - Сметания инвентаря?

**Comment by Romsik788** [comment]
if you knew the Russian language, then they understood that "Сметания инвентаря" is an inappropriate phrase.

**Comment by MJRLegends** [comment]
Haha rip

**Comment by radfast** [comment]
oh!

**Pull request merged**
