### PR TITLE
Added trade with Moon villagers [MC 1.7.10]

### PR DESCRIPTION
**Pull request by gug2**

### CODE REVIEW

**Comment by Restioson** [comment]
Unfortunately, this mod is dead :(

**Comment by EzerArch** [comment]
Excellent. Just a question: after a quick look at the code, it seems the alien villagers would be able to breed, wouldn't they? Still using the same vanilla way?

**Comment by gug2** [comment]
Why not? They should have the right to life :D

**Comment by gug2** [comment]
In any case, you can edit my code (if you don't want villagers to breed)

**Comment by EzerArch** [comment]
> In any case, you can edit my code (if you don't want villagers to breed)

Hmmm.... I was asking if alien villagers would breed based on the same vanilla way, that is, by door count per village.

**Comment by gug2** [comment]
I think it would be better :D

**Comment by C1ffisme** [comment]
Do they have the same trades as normal villagers? It might be interesting if you traded cheese for items, since there are no emeralds on the moon.

**Comment by gug2** [comment]
At the moment I make up recipes for trade

**Comment by gug2** [comment]
I have successfully created the recipes for trade

**Comment by gug2** [comment]
I Plan to add a translator:

translator

Item which will be trade with moon villagers
Without it, the trade GUI will NOT open
For item will make a separate slot

What do you think? :)

**Comment by C1ffisme** [comment]
@gug2 Seems good, although if you do require a translation item, maybe buff the villager's trades a tiny bit for balance.

**Comment by dj3520** [comment]
Feel like the frequency module can act like the planned translator item. For example, without it you can't hear/understand the alien villagers. Already has it's own slot and would make it a bit more useful.

**Comment by gug2** [comment]
@dj3520 Great idea! bring it to life!

**Comment by C1ffisme** [comment]
@dj3520 Seems okay, since it's only use at the moment is "tracking" entities and hearing on airless planets, which you really don't need to do so anyway, unless you are creeper paranoid.

**Comment by gug2** [comment]
Thanks!
https://github.com/micdoodle8/Galacticraft/commit/bc5f4414366992eb1461a074e3560a5698cef1ab

**Pull request closed without merging**
