### PR TITLE
Fix Venus Entry Pod rendering

### PR DESCRIPTION
**Pull request by SteveKunG**

### CODE REVIEW

**Comment by micdoodle8** [comment]
Thanks.

Is the parachute offset wrong? Doesn't look right in those screenshots.

**Comment by SteveKunG** [comment]
Yes. I've included fix for this issue.

Before and After

**Comment by micdoodle8** [comment]
Oh, I missed that change. Thanks again :)

**Comment by EzerArch** [comment]
Ignore this, just for LULZ:

**Pull request merged**
