### PR TITLE
[1.8-1.11] Achievements

### PR DESCRIPTION
**Pull request by marcus8448**
[The PR can be merged now]
This PR adds achievements for Galacticraft (Including GCPlanets).
Note: Please __do__ comment on what the names for the achievements should be.

### CODE REVIEW

**Comment by EzerArch** [comment]
When it's ready I'll nag the devs. ;)

**Comment by marcus8448** [comment]
Ok, the PR is ready to be merged with #3527.

(Just so you know): On the GC wiki main page radfast took both twitter links. (I don't have access to edit it)

**Comment by EzerArch** [comment]
Thank you.

As to the wiki page, only Radfast can edit that but he's been away on vacation. If he doesn't answer we'll need to wait. :)

**Comment by radfast** [comment]
Huge thanks @marcus8448 for this, it's a nice addition.

I'm happy with the text, especially for the Moon.  (We may find that some languages e.g. Russia and China want to change the text in their language to make it not so US-centric, and that's also OK)

As it's your addition, I think you should have creative control over it - so if you want to change the text for Mars, Venus, Asteroids later, definitely feel free to do that.

**Comment by radfast** [comment]
I've fixed the degrees symbol, not sure what happened there.  It's best to use a Unicode-capable text editor for these language files.  On a Windows machine, the in-built WordPad is OK for this, but not NotePad.  Or your IDE may have a full text editor.

**Pull request merged**
