### PR TITLE
World Gen fixes

### LINKED ISSUE #3013: No slimeling eggs on Mars
* Minecraft version: 1.10.2
* Galacticraft version: 80 - 118
* Forge version: 2316
* Single player (SSP) or Multiplayer (SMP)? SSP
* Galacticraft add-ons and other mods installed? No

Mars terrain is not generating slimeling eggs. (ref.: https://forum.micdoodle8.com/index.php?threads/where-are-the-slimeling-eggs.6827) 

I've tested the builds 118, 112, 106, 100 and 80.

### PR DESCRIPTION
**Pull request by SteveKunG**
Fixes #3013 

~~Why I remove BiomeDecoratorSpace?~~
~~- I saw only Mars use this class and the others use vanilla Biome Decorator. So I think this unnecessary.
Note : This may break other add-ons that use this class. (But not my add-on)~~

### CODE REVIEW

**Comment by EzerArch** [comment]
Thank you!

**Comment by SteveKunG** [comment]
@radfast I'll revert Remove Biome Decorator commit later tomorrow.

**Comment by SteveKunG** [comment]
@radfast Sorry for late, Is this looking good for you?

**Comment by radfast** [comment]
Huge thanks @SteveKunG for finding the 2 problems (unwanted ```* 16``` in ```BiomeDecoratorSpace```, and also failure to check eggs are on surface blocks).

But the solution in your PR seems too complex, too many changes (or maybe I did not understand it?).  I made this, does this look OK to you?   https://github.com/micdoodle8/Galacticraft/commit/98ade49fc24b118358c0ebdf000c28ba2313b6ae

**Comment by SteveKunG** [comment]
Yes, Egg generation works fine. So next time I should explain that more understand what I do.

**Pull request closed without merging**
