### PR TITLE
Allowed to charge all electrical items in IC2 chargers.

### PR DESCRIPTION
**Pull request by BlesseNtumble**
Tools, Armors, etc

### CODE REVIEW

**Comment by BlesseNtumble** [comment]
And 1.7.10 file:
``
public class ElectricItemManagerIC2_1710 implements IElectricItemManager
{
    @Override
    public double charge(ItemStack itemStack, double amount, int tier, boolean ignoreTransferLimit, boolean simulate)
    {
        if (itemStack.getItem() instanceof IItemElectric)
        {
            IItemElectric item = (IItemElectric) itemStack.getItem();
            if (amount > item.getMaxCharge(itemStack))
            {
                amount = item.getMaxCharge(itemStack);
            }
            float energy = (float) amount * EnergyConfigHandler.IC2_RATIO;
            float rejectedElectricity = Math.max(item.getElectricityStored(itemStack) + energy - item.getMaxElectricityStored(itemStack), 0);
            float energyToReceive = energy - rejectedElectricity;
            if (!ignoreTransferLimit && energyToReceive > item.transferMax)
            {
                energyToReceive = item.transferMax;
            }

            if (!simulate)
            {
                item.setElectricity(itemStack, item.getElectricityStored(itemStack) + energyToReceive);
            }

            return energyToReceive / EnergyConfigHandler.IC2_RATIO;
        }
        return 0D;
    }

    @Override
    public double discharge(ItemStack itemStack, double amount, int tier, boolean ignoreTransferLimit, boolean externally, boolean simulate)
    {
        if (itemStack.getItem() instanceof IItemElectric)
        {
            IItemElectric item = (IItemElectric) itemStack.getItem();
            float energy = (float) amount / EnergyConfigHandler.TO_IC2_RATIO;
            float energyToTransfer = Math.min(item.getElectricityStored(itemStack), energy);
            if (!ignoreTransferLimit)
            {
                energyToTransfer = Math.min(energyToTransfer, item.transferMax);
            }

            if (!simulate)
            {
                item.setElectricity(itemStack, item.getElectricityStored(itemStack) - energyToTransfer);
            }

            return energyToTransfer * EnergyConfigHandler.TO_IC2_RATIO;
        }
        return 0D;
    }

    @Override
    public double getCharge(ItemStack itemStack)
    {
        if (itemStack.getItem() instanceof IItemElectric)
        {
            IItemElectric item = (IItemElectric) itemStack.getItem();
            return item.getElectricityStored(itemStack) * EnergyConfigHandler.TO_IC2_RATIO;
        }
        return 0D;
    }

    @Override
    public boolean canUse(ItemStack itemStack, double amount)
    {
        if (itemStack.getItem() instanceof IItemElectric)
        {
            return this.getCharge(itemStack) >= amount;
        }
        return false;
    }

    @Override
    public boolean use(ItemStack itemStack, double amount, EntityLivingBase entity)
    {
        if (itemStack.getItem() instanceof IItemElectric)
        {
            return this.discharge(itemStack, amount, 1, true, false, false) >= amount - 1;
        }
        return false;
    }

    @Override
    public void chargeFromArmor(ItemStack itemStack, EntityLivingBase entity)
    {
    }

    @Override
    public String getToolTip(ItemStack itemStack)
    {
        return null;
    }

}
``

**Comment by radfast** [comment]
This is needed because your mod implements ```IItemElectric``` but does not use ```ItemElectricBase```?

**Comment by BlesseNtumble** [comment]
Armor inherits ItemArmor, not ItemElecticBase

**Comment by radfast** [comment]
I had to take a different approach because [this line](https://github.com/micdoodle8/Galacticraft/blob/84e0d9a241d33a5abf91372b91666aee1a194453/src/main/java/micdoodle8/mods/galacticraft/core/energy/item/ElectricItemManagerIC2.java#L26) references a field which exists only in ```ItemElectricBase```.

I made a new API interface ```IItemElectricBase```.

This should also be backwards-compatible with existing addons which simply extend ```ItemElectricBase```.

**Pull request closed without merging**
