### PR TITLE
Made the amount of oxygen collected to not be hard coded.

### PR DESCRIPTION
**Pull request by Quarris**
Allows the value to be changed by addons.

### CODE REVIEW

**Comment by marcus8448** [comment]
Why would addons need to change the value?

**Comment by TheQuadShot** [comment]
I don't understand the need for this as well. I don't recall seeing anything here(issues) or on the forums asking for or needing this functionality.

**Comment by Quarris** [comment]
It'd be useful to have this changed (and also other values) to change the amount of oxygen produced from plants. Me and my friend are making a modpack focused around "living" on mars and starting of in a confined space and would be nice if there was a way to power the oxygen with a few potatoes. I haven't created an issue because honestly I can see changing things like this to make them configurable a pain, but I can do that instead.

**Comment by micdoodle8** [comment]
I don't see why not. I've committed your edits myself with a few minor changes.

**Comment by Quarris** [comment]
Surely making it final would make the same problem of not being able to change it?

**Comment by micdoodle8** [comment]
Ah, my mistake - fixed now.

**Comment by Quarris** [comment]
Thank you!

**Pull request closed without merging**
