### PR TITLE
Remove debug message

### PR DESCRIPTION
**Pull request by SteveKunG**

### CODE REVIEW

**Comment by radfast** [comment]
In recent 1.8 testing, I have sometimes seen Netty errors from ConnectionPacket with packet 103.

I guess this is something @micdoodle8 is currently still looking at.

**Comment by SteveKunG** [comment]
Same here. I got a crash log from connection packet : http://pastebin.com/VE9gDy7X
I will close this.

**Comment by radfast** [comment]
I think leave this open, as a reminder to fix this issue.  (There is no other issue report)

**Comment by micdoodle8** [comment]
Wasn't still looking at anything, just simply forgot to remove it :) Thanks

**Pull request merged**
