### PR TITLE
Update nl_NL.lang

### PR DESCRIPTION
**Pull request by HellThunder**
I accedently did delete a sentence again hope you can fix it...

gui.fuelOutput.desc.1=

### CODE REVIEW

**Comment by radfast** [comment]
Can you edit the file to put that line back?

**Comment by HellThunder** [comment]
does it matter where the line is

**Comment by radfast** [comment]
gui.fuelTank.desc.1=fuel loader to fill

**Comment by HellThunder** [comment]
thx

**Comment by radfast** [comment]
Thank you, all looks good.

**Pull request merged**
