### PR TITLE
[1.12.x] Improve JEI Implementation

### PR DESCRIPTION
**Pull request by CDAGaming**
APIs Updates & Status:
 - JEI (Implementation Improved, Tested as Working, #2887 Issues Fixed)

Let me know of any other Issues found in this, as I hope everything Implemented so far works as it should.

**Part 2/2 of PR Bundle**

### CODE REVIEW

**Comment by radfast** [comment]
For JEI, please see https://github.com/micdoodle8/Galacticraft/commit/26c526d7982a93736bf1dabc9537ddd5f84bad22.   It was better to update JEI to 4.5.0 in Galacticraft 1.11.2 using SteveKunG's pull request which I think is better code - for example see the overrides of .registerCategories().  From there, the update to JEI 4.8.5 is straightforward and does not need too many changes to Galacticraft code.

For the other APIs, I have already suggested to you that it is better if I update the APIs.  However, I greatly appreciate the work you have done already on these.  I think the project can benefit from your help on some of the unassigned issues.

**Comment by CDAGaming** [comment]
I can adjust the JEI commit to align to that PR (Most of what was on that PR has already been applied but I can apply the other enhancements). The Other API commits are here mainly to speed up the process (should you need/want the extra help :) ). So far, all I have left is Mekanism then testing the other mods. So far, everything's looking good

**Comment by CDAGaming** [comment]
I saw the recent JEI Updates to 1.12 branch. Will adjust my commit accordingly, stay tuned.

**Comment by border999** [comment]
As of 1.12.2, I believe it is best to remove compatibility with minefactory reloaded or discontinue with it's upgrading. Seeing as the mod no longer appears to be being updated. I would instead recommend the starting of compatibility with it's spiritual successor, Industrial Foregoing.

**Comment by radfast** [comment]
thanks @border999 -  the main "compatibility" feature we added is a feature to prevent the MFR AutoSpawner from mob spawning with full NBT datacopy, where the mob is a Galacticraft Slimeling.  The reason is to prevent item duplication because Slimelings carry an inventory - similar to the way that spawning a vanilla Donkey with full NBT copy would duplicate items.

do you know if Industrial Forging has a similar mob Auto Spawner which spawns exact copies of mobs?

**Comment by CDAGaming** [comment]
I've Rebased this PR and Redid some things with JEI and Galacticraft. Now working on Testing Mekanism.

**Comment by border999** [comment]
@radfast It was designed to be similar to MFR but I don't have any ideas as to what it looks like under the hood. The creator doesn't have a github for the mod so I can't provide the mob or class information. You would have to talk to the mod author for those. I apologize for not having any other information.

**Comment by radfast** [comment]
> The creator doesn't have a github for the mod so I can't provide the mob or class information.

Not a good start, if looking for compatibility with other mods :)  I think I'll leave this one.

**Comment by CDAGaming** [comment]
Edited my comment on the Issue Page. That Optifine Issue was one I caused on accident, so just the Overworld/Planet Switching Bug is there.

**Comment by border999** [comment]
@radfast He actually does have a github apparently. https://github.com/Buuz135/Industrial-Foregoing

**Comment by border999** [comment]
and a discord if you look at industrial Foregoing's curseforge for the link

**Comment by radfast** [comment]
@CDAGaming  it's kind of you to take the time to update the other mod APIs.

But this isn't going to work like this, for several reasons::
*   I can't / won't merge WIP PRs
*   I would like to see a separate PR for each separate API, this is to keep things tidy and logical in the changelog, also because each separate API is a lot of work by itself and I don't like monster-sized commits, also this will allow each API to be tested separately
*   I will want to review and test what you have done for each API very carefully if you're doing it - really I'd rather be doing all the API updates myself, as I have previously posted - this is in part because there are several places where we use Java reflection to access other mod APIs and if you are relatively new to coding in Java, reflection is not where you want to be starting...

Alternatively, if you are happy to continue this PR as a single convenient hub for all your API updates, then I can cherry pick commits I guess - or more likely retype things myself but looking at your commits for assistance - but then you won't get any credit in the repo.

------

Just looking at the JEI API: I have already updated the JEI API, but you are proposing a commit with more changes to what I have done: please explain the exact reason for each of your changes.

**Comment by CDAGaming** [comment]
1) As i think i mentioned earlier, It's only still as WIP due to the fact I need to test the new APIs more closely (Which I am working on at this time)
2) Once I remove the WIP Label, most likely I'll close this and split up the API Upgrades in their Respective areas.
3) The JEI Commit just merely removes the use of some Deprecated methods (BlankModPlugin for one) as well as Removes the Now-Nonused Imports from your JEI Update Commit and some minor code cleanups from my previous version of the JEI Upgrade

@radfast

**Comment by radfast** [comment]
>  some minor code cleanups from my previous version of the JEI Upgrade

To the extent there's a diff between your code and mine which is currently in the repo, please explain this more... ?   Deprecated BlankModPlugin I can understand but the current code using it works fine, so it's not a necessary change.  Nonused imports have been cleaned up in GC code in https://github.com/micdoodle8/Galacticraft/commit/baf04ac1424097bfbd56d9d11f2b94c8868f37fd

**Comment by CDAGaming** [comment]
I am still in progress of rebasing this, just have not gotten to it just yet...

**Comment by radfast** [comment]
I have now made proper commits for **PlayerAPI** and **Biomes o' Plenty** and tested these in-game.  For PlayerAPI it looks like your commit used an older version of PlayerAPI (maybe 1.12?), anyhow the obfuscated names were incorrect

**Comment by CDAGaming** [comment]
Hm, Odd. Couldv'e swarn I grabbed it from 1.12.2

Anyways, I'll rebase this for the rest of the API Updates/Adjustments to JEI

**Comment by CDAGaming** [comment]
Rebased. All Commits have links to where the API was taken from (Commit-wise)

**Comment by radfast** [comment]
All of these are now in the repo - are you happy if we close this?

**Comment by CDAGaming** [comment]
Well, I'd rather rebase it for Updating the JEI Implementation, as that's the only commit that hasn't been merged. I'll change the Title and rebase to reflect this @radfast

**Comment by radfast** [comment]
Re: JEI see my comment above:

>    To the extent there's a diff between your code and mine which is currently in the repo, please explain this more... ? Deprecated BlankModPlugin I can understand but the current code using it works fine, so it's not a necessary change. 

Why are you saying Galacticraft needs to be coded differently here?

**Comment by CDAGaming** [comment]
Going to Update this for Just Deprecating BlankModPlugin as that's the only real necessary change here, and so this can get merged hopefully :D

**Comment by radfast** [comment]
like I said, I don't see deprecating BlankModPlugin as a _necessary_ change.  If mezz removes BlankModPlugin in 1.13 then we can look at doing that in 1.13 ... if we ever make a Galacticraft 1.13 that is, I'm really not sure that we will, or it might have to be somebody else not me.  (Minecraft 1.13 is expected to be a very challenging update for mods.)

**Pull request closed without merging**
