### PR TITLE
[Feature Request] Evolved Enderman and Evolved Witch

### PR DESCRIPTION
**Pull request by SteveKunG**
Screenshots

I also changing spawn rate (Default vanilla spawn rate).

### CODE REVIEW

**Comment by Dream-Master** [comment]
Nice idea hopfully available for 1.7.10 too?

**Comment by SteveKunG** [comment]
Sorry, I focus on 1.8.9+ only.

**Comment by radfast** [comment]
Hi @SteveKunG 

I talked to @micdoodle8 about this

The graphics look great.

We really like the Evolved Enderman, he will fit nicely into the game in the Asteroids dimension.

Our ideas for the core Galacticraft planets (Moon, Mars, Venus) don't include Evolved Witch spawning - except one thing (*) - but we can include the Evolved Witch as a registered entitiy in the core mod so that you can spawn Evolved Witch on your planets if you want that?

(*) Currently Alien Villager will transform into a Witch if struck by lightning.  This can be Evolved Witch...

**Comment by SteveKunG** [comment]
OK, I'll remove Witch spawning. Should I re-create this pull request? (Conflict file)

**Pull request closed without merging**
