### PR TITLE
Update th_TH.lang

### PR DESCRIPTION
**Pull request by SteveKunG**

### CODE REVIEW

**Comment by SteveKunG** [comment]
I can't create a new pull request. I have no idea why.
(I'm a new for GitHub Desktop.)

**Comment by radfast** [comment]
Please don't mix language updates and code changes.

When you have time, please can you make a screenshot for 7c32000 because I do not understand what has changed - you seem to be changing 2 different things here.

**Comment by SteveKunG** [comment]
Somethings like this.

**Comment by micdoodle8** [comment]
Looks alright, merging. But yeah try to keep pull requests separate for different changes please.

**Comment by SteveKunG** [comment]
Thank you. I'll reopen my 1.8 changes.

**Pull request merged**
