### PR TITLE
JEI Improvement

### PR DESCRIPTION
**Pull request by SteveKunG**

### CODE REVIEW

**Comment by SteveKunG** [comment]
Suggestion : Combined all NASA Workbench recipes into one type?

**Comment by micdoodle8** [comment]
So this change makes the icons appear instead of using the first two letters of the category (E.g. "Co" for compressor)?

**Comment by SteveKunG** [comment]
Yes, it can customize an icon from ItemStack into recipes window.

IModRegistry#addRecipeCategoryCraftingItem is available in 1.8.9 as well. I can create pull request for 1.8.9 if you want.

**Comment by micdoodle8** [comment]
Okay, great. 

Yeah that'd be best, we're trying to keep code differences as small as possible between the three versions.

**Comment by SteveKunG** [comment]
Oops, this not available in 1.8.9 JEI API. Re-opening this.

**Comment by micdoodle8** [comment]
Okay, merged. Thanks!

**Pull request merged**
