### PR TITLE
Update Mekanism API in 1.10. Close #2780

### LINKED ISSUE #2780: [1.10.2] Mekanism API changed in final 1.10.2 Mek version
There's an issue with the current version of the Mekanism API you're using.
It crashes with the following log:
https://pastebin.com/H4Yq1e19

The Mekanism API has changed a bit and the interface you're using isn't anymore in the API. ~I'll look whether it's moved or deleted ;)~
The interface ICableOutputter has changed in https://github.com/aidancbrady/Mekanism/commit/cf6a04a65daa413179e777a19bb9f7a8ba5c30e0 to (not 100% sure) IStrictEnergyOutputter

Reference: aidancbrady/Mekanism#4403

### PR DESCRIPTION
**Pull request by thommy101**

### CODE REVIEW

**Comment by MJRLegends** [comment]
I need this pull request to be merged and released so much haha :D its causing me pain with issues due to it haha @radfast you know you love us. Haha

**Comment by radfast** [comment]
Thank you very much for this, hugely appreciated that you made a PR with the needed changes to our code as well.

I've now implemented this as https://github.com/micdoodle8/Galacticraft/commit/0811eb3d30b53ac757b665dfbca3b25eb10c38fb - I'm looking to preserve compatibility with legacy builds of Mekanism as well as the 1.10.2 final build.

_(Note: we do not distrbute the Mekanism API with our mod, it's only for compiling our mod against, therefore it should not damage anything for us to hack about the API classes like this.)_

Tested working with both Mekanism-1.10.2-9.2.2.301 and Mekanism-1.10.2-9.2.2.fix3.

OK the gas pipes are not working currently with our oxygen machines, that's a separate issue I need to work on - and because it's not currently working I'll probably only make that compatible with Mekanism 1.10.2 final.

One other thing causing minor problems, our TileEntityUniversalSource is not being detected by [CableUtil](https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/util/CableUtils.java#L82) as an outputter, but I can't figure out why ...  doesn't work in either legacy or final Mekanism, so that Galacticraft energy storage will not output into Mek universal cable.

**Comment by thommy101** [comment]
As long as it works I'm happy. Nice idea to make it work with both versions!

I'll write down the cable issue and look at it when I've got some time ;) Maybe open an issue over at Mekanism so I won't forget and maybe others can take a look. Mekanism currently has 2 extra devs to speed up developement.

**Comment by radfast** [comment]
Don't worry about the cable issue, I figured it out ... just needed to use the in-game Configurator to put the cable into "PULL" mode.

I'm now seeing if we can emulate ```CableUtils.emit_do()``` so that it works even without PULL mode.

**Pull request closed without merging**
