### PR TITLE
[1.12.2] API Feature - Add ability to change an existing Space Station recipe

### PR DESCRIPTION
**Pull request by MJRLegends**
Part of my request at #3120

I only made it for MC 1.12.2 because i only needed it for MC 1.12.2 but feel free to add it for MC 1.8+ too :P 

Proof of working:

### CODE REVIEW

**Comment by radfast** [comment]
Incorporated in all versions, I want to keep the API consistent across all GC4 versions as much as possible.

**Comment by MJRLegends** [comment]
No problem :D yeah i thought that was the case, i will make sure to always do 1.8+ for api things :D

**Comment by MJRLegends** [comment]
@radfast Hey just wondering whats the eta for the next update, i only ask as im going to be updating a few of my mods after build 138 of GC.

**Comment by radfast** [comment]
tonight i hope

**Comment by MJRLegends** [comment]
@radfast If you got time i would really appreciate if you would take a look at my other pull request. Don't worry if you dont have time.

**Comment by MJRLegends** [comment]
@radfast btw the 1.12.2 dev builds failed on jenkins, dont worry about fixing them now as ive already built my own to use so no rush to fix it today. Also appreciate your work you put in to Galacticraft :) just finished doing 15 mod updates for multiple mods and multiple mc versions and uploading them to curseforge :)

**Pull request closed without merging**
