### PR TITLE
1.12.2 only, Changed GC Planets registering recipes to match GC Core system

### PR DESCRIPTION
**Pull request by MJRLegends**
Fixes https://github.com/micdoodle8/Galacticraft/issues/3514

This pull requests move everything that isnt mod compact recipes to the RegistryEvent.Register<IRecipe> event to match the GC Core which already has this. 

I need this to fix GalacticraftTweaker issues
https://github.com/MJRLegends/GalacticraftTweaker/issues/4
https://github.com/MJRLegends/GalacticraftTweaker/issues/6

Would be amazing if it could be merged

### CODE REVIEW

**Comment by micdoodle8** [comment]
Why just 1.12.2? This is an issue in all versions we maintain, right?

**Comment by MJRLegends** [comment]
Maybe but i believe it was only changed for 1.12.2 due to the event system in forge now requires registering in the events that run between pre int and init. And this change that this matches in GC core was only for 1.12.2 too

**Comment by MJRLegends** [comment]
This is the commit it was changed for GC core https://github.com/micdoodle8/Galacticraft/commit/07aa2cac87bdae3a5709a3564f052958009fe4b6

**Comment by micdoodle8** [comment]
Alrighty, thanks for your work here!

**Comment by MJRLegends** [comment]
@micdoodle8 thank you, any chance you put trigger a jenkins build plz

**Pull request merged**
