### PR TITLE
[Sponge] Fix dungeon generation on the moon

### LINKED ISSUE #3789: Incorrect dungeons generation
- Minecraft version: **1.12.2**
 - Forge version: **14.23.5.2838** (or **14.23.5.2846** on the test server)
 - Galacticraft version: **1.12.2-4.0.2.237** (also with earlier builds)
 - **SpongeForge** version: **1.12.2-2838-7.1.7-RC3908**
 - Java version: **1.8.0_222/64-bit**

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? **Multiplayer**

All other mods are disabled. The entrance room is not generated at all. Corridors are generated blocked quite often.

<details><summary>Screenshots: Dungeon</summary><p>

</p></details>

<details><summary>Screenshots: Another dungeon. Corridor blocked in several places.</summary><p>

</p></details>

_It could also be caused by some kind of bug in Sponge..._

### PR DESCRIPTION
**Pull request by marcus8448**
Fixes #3789

It's definitely not the nicest way to do it, so it only changes logic if sponge is loaded.

### CODE REVIEW

**Comment by clienthax** [comment]
> Fixes #3789
> 
> It's definitely not the nicest way to do it, so it only changes logic if sponge is loaded.

What is the actual issue here on the sponge side?

**Comment by MJRLegends** [comment]
Probably sponge mixin overriding stucture methods causing something to get conditioned out for working

**Comment by MJRLegends** [comment]
But hard to tell since so many commits making it confusing to see changed at once

**Comment by micdoodle8** [comment]
Yikes, unfortunate that this is necessary, but thank you for the fix. Merging now.

**Pull request merged**
