### PR TITLE
Add more colors to fluids

### PR DESCRIPTION
**Pull request by dj3520**
Most of the fluids are indistinguishable from each other. This problem is simple enough for me to solve myself.
prev
If anyone doesn't agree with the color scheme, it's not too hard for me to change.
**If there is any conflict with another mod's liquid looking too similar, please let me know**
* All based on Atmospheric Gases texture, which is unchanged.
* All gases (except methane) are largely transparent (40%)
* Methane gas resembles fuel, but is darker.
* Oxygen gas and LOX are simply different transparencies but can be told apart.
* Liquid Argon follows GUI color (somewhat)

I can't test Liquid Methane since I don't see how to obtain it, but is opaque. Methane textures don't match transparencies because they otherwise blend in.

### CODE REVIEW

**Comment by radfast** [comment]
I understand the objective which is to be able to tell which liquid something is on sight, and appreciate the work which must have gone into this.

But sorry to say but personally I don't like this colour scheme, it's too colourful - looks like Jelly Beans or Candy Crush. :p 

If this is going to happen at all, the colours need to be subtle, and the transparency needs to be higher for both liquids and gases.

I also really have in mind an animated texture for the LOX and other liquids which changes a lot more, so it looks like the liquid is always boiling, but I don't have the skills to make that myself.  Most Minecraft fluid textures are based on a "calm water" level of animation, but it does not have to be that way...

**Comment by dj3520** [comment]
>the work which must have gone into this

What, 3 minutes of picture editing, 20 seconds forking, 2 setting up git on my friend's server (shh) and then putting in the PR? No prob I guess.

>the colours need to be subtle

So mostly white but still tinted per say? This is known as low saturation. Easy to apply.
>transparency needs to be higher for both liquids and gases.

Except for methane, gases are 40% and liquids 70%. Going more translucent makes it hard to see if it's there or not. Methane appeared this way and is now 70% and 100% respectively. I could turn this up higher but I think you should see it as it plays first. The tanks in the picture are all behind RC tin blocks so that Mars doesn't blend in. Let's change that:
image
I could probably go another 10-15% lower I suppose.

>animated texture for the LOX and other liquids

To my understanding that would have to be a png sequence.

>Candy Crush

I've never actually played this.

**Comment by radfast** [comment]
> To my understanding that would have to be a png sequence.

The texture for a fluid is a single .png file with dimensions 512 x 16.  The actual fluid in-game has a 16 x 16 texture but every tick (or frame, I'm not too sure) the game moves which part of the .png it's using (like the u stays the same but the v changes) so you have an animation with 32 different possible textures.  That's why still water in Minecraft has a "gently moving" appearance.

To make the LOX appear boiling, it would need a lot of work on that texture.

**Comment by dj3520** [comment]
I see. But making it appear boiling in a tank might prove challenging,
since I'd believe the fluid's texture is rendered as a box, meaning there's
no "top" side. Also this might look strange for Railcraft: I think the
texture gets stretched for different tank sizes.

**Comment by micdoodle8** [comment]
Honestly, I kind of like this color scheme. I completely agree with making things realistic in some cases for this mod's development, but I think the liquids should be clearly distinguishable from a fair distance. It fits in well with other mod's bright color schemes (so it won't really stick out too much) and with a lot of greys and blacks in Galacticraft's color scheme, I think I'm going to merge it adjust the transparency slightly.

**Comment by dj3520** [comment]
I'm perfectly fine with adjustments since realistically that's all I really
did. Can't say I'm talented enough to make the bubbling gas texture, but if
someone else does it's easy for me to change the color.

**Comment by dj3520** [comment]
Can I suggest/request that the colors be matched to what they show in the interfaces of the machines? I don't particularly care who changes to match, but the difference in colors are a bit strange. I'd be easy to match on my end if I got the RGB values.

**Comment by C1ffisme** [comment]
Can I see a comparison of fuel and methane gas? Just curious on how different they look.

**Comment by dj3520** [comment]
I purposely made methane close to fuel since it's one step away. Still easy to tell the difference.
image

**Pull request merged**
