### PR TITLE
Phobos and Deimon on Mars sky. Added rotation stars.

### PR DESCRIPTION
**Pull request by BlesseNtumble**
Added rotation stars and added Phobos and Deimos on Sky.

### CODE REVIEW

**Comment by radfast** [comment]
Nice idea.  I'll try it out and if all looks good, will merge this later today.  With a config option I think, because these are not square ...

**Comment by EzerArch** [comment]
I like them, but they are *a bit* too high definition for Galacticraft style, near photo-realistic in my opinion. The current GUI's celestialbodies icons range from 8x8 to 16x16 px in size. Those are 48x48 px.

**Comment by SteveKunG** [comment]
+1 If it possible :) @radfast Can I changing rotation stars on the moon and improvement Asteroids Sky rendering?

**Comment by BlesseNtumble** [comment]
@SteveKunG Asteroids rotate X. Not with respect to Y.

**Comment by SteveKunG** [comment]
Oh. I mean the earth in the asteroids sky. We can see the earth from asteroids?

**Comment by BlesseNtumble** [comment]
@SteveKunG in telescope...

**Comment by radfast** [comment]
> Can I changing rotation stars on the moon and improvement Asteroids Sky rendering?

Sure.  Please make each improvement in a **different Pull Request**.

**Comment by micdoodle8** [comment]
Closing for now, it's possible that this will be re-visited at a later date.

**Pull request closed without merging**
