### PR TITLE
[1.11 +] Stop using Deprecated FMLRelaunchLog for logging

### PR DESCRIPTION
**Pull request by marcus8448**

### CODE REVIEW

**Comment by radfast** [comment]
hi marcus8448 - thank you for this PR.

I have some questions about it:

1.  In which version did FMLRelaunchLog become deprecated?  I thought it was in 1.12.2 not 1.11.2 - certainly seems not deprecated in Forge 1.11.2-13.20.0.2282 which is the version we are targeting in Galacticraft's 1.11.2 branch.

2.  Shouldn't we use ```FMLPreInitializationEvent.getModLog()``` instead of creating a new ```org.apache.logging.log4j.Logger```?


For your future PRs they can be merge more smoothly and credited to you if you take care to respect our code style.  For example we have opening curly braces on a new line, and 4 spaces for indents, not tab characters.

Are there any areas of the mod you are especially interested in improving / fixing / adding new features?  I could certainly use some help :)    I have a list of about 50 new features planned but as you can see from the commits I am spending the majority of my coding time dealing with issues, polishing what's already here but not working 100%, and maintenance...

**Comment by marcus8448** [comment]
Hi @radfast so here is what I got:
1. Build 1.11.2-13.20.0.2345 is when it got deprecated
2. Technically they are the same they both use `org.apache.logging.log4j.Logger` 

I will try to do that next time, and it is ok if I do not get credited :)

**Comment by radfast** [comment]
OK thank you that is very helpful.

We support a range of Forge versions in 1.11.2 including the older versions, for widest compatibility (for example, this lets older modpacks update their Galacticraft to have our latest bugfixes, without breaking anything else).

Therefore I will not change this in 1.11.2 - I'm comfortable with using a deprecated method.  I will change this in 1.12.2.  I plan to look to see if it's possible to do this by updating ```GCLog``` only, I don't want to change all other classes if I can help it, because a lot of 1-line changes like that will make it harder to auto-merge future code from 1.11.2 up to 1.12.2.

Leaving this open as a reminder for me until that is done in 1.12.2 ...

Please do feel free to make more PRs...

- If your PRs can be merged immediately then you will get Contributer status on this project.

- PRs which fix a currently open issue are most welcome

- Same for PRs which fix anything else which is obviously broken.  Generally it's best to minimise the number of lines of code which change, as this makes maintenance between the 4 different current branches easier.

- We regularly automerge code from ```master``` -> ```MC1.10``` -> ```MC1.11``` -> ```MC1.12```.  (It's a nightmare, but we are pretty good at it by now!)  Therefore generally your PRs should target ```master``` branch unless the issue / fix is only relevant to a later Minecraft version, in which case target the first branch where it applies.

- It's best to discuss your plans for any major change with us first, before you spend hours coding it.  We are very open to discussing improvements.

-  (We are not big fans of PRs which are purely a question of personal taste or enforcement of textbook coding style or "tidyness" - especially if these things _hurt_ the game's performance...  )

**Comment by marcus8448** [comment]
Ok so @radfast are you going to do this in 1.12.2 or can I look into this w/o making 1 line changes?

**Comment by radfast** [comment]
I'm happy to do it in 1.12.2, now you've shown me that it is needed.  I'll close this.

As it's clear you know how to code  :)   I'd like to warmly encourage you to look more widely at Galacticraft.  Maybe there's something else you can see should be fixed or improved ... ?
https://gist.github.com/radfast/2021bf0b6e57fdd5c95e337b5ab48039

**Comment by marcus8448** [comment]
Ok @radfast I probably will not do any features right now because I am fairly new (actually very new) to coding so do not expect much from me.

**Pull request closed without merging**
