### PR TITLE
Idea Preview for changes for issue #3104

### PR DESCRIPTION
**Pull request by MJRLegends**
For issue #3104

Ok so i have made a working change to this config option, im open to making changes.

Proof of working concept:

### CODE REVIEW

**Comment by radfast** [comment]
Nice idea.  I will incorporate this, but I need to merge it manually for three reasons:

1.  You haven't respected our code style in all places, for example opening braces

2.  For future-proofing, I think the stoneBlock should be a CelestialBody parameter - this is part of my more general plan to have all / most world features in CelestialBody.

3.  I think we should keep ONLYMOON and ONLYMARS for compatibility with people who have existing configs setup, it's not only your modpack using this....

I will leave this open until done!

**Comment by MJRLegends** [comment]
No problem yeah this was more a idea preview than a full formatted change

**Comment by MJRLegends** [comment]
Would you like me to help by doing a rebase on this pull request or make the changes you listed above @radfast

**Comment by MJRLegends** [comment]
@radfast Would you like any help with getting this to a point where it fits in with the current api/how you and micdoodle plan to do the api? I would be amazing to see this added..

**Pull request closed without merging**
