### PR TITLE
[1.12.x] (WIP) Updates for 1.12

### LINKED ISSUE #3084: [1.12.x] Workspace Setup - Access Transformer Issue
**Sorry In Advance if this is in fact the wrong place to be posting this**

I'd Like to test out Galacticraft on 1.12 as you guys work on developing it, however, during setupDecompWorkspace it has the following error: [Build Error via Hastebin](https://hastebin.com/yefofixewi.lua)

If anyone can tell me what might be wrong, I'd Greatly appreciate it 
(Or if this is the wrong place to post this type of issue, to be redirected to where i can get support for this)

### PR DESCRIPTION
**Pull request by CDAGaming**
Changes:
- Add Gradle Wrapper
- Updates MCP (20180108) + Forge (Minor Function Changes - 2555 to 2586)
- Adjust .gitignore to now ignore files generated during runClient/runServer
- Updates JEI Access Transformer for 1.12 (Functions were Replaced in 1.12; Fixes #3084)
- origin/master Merge
(Unfortunately with one commit exclusion; didn't Know the New Way to Register Biomes so left that Bit out)

ToDo:
 - Update Mekanism API
 - Update MineFactoryReloaded (Port Progress: https://github.com/CDAGaming/MineFactoryReloaded)

APIs Updated:
 - JEI (https://github.com/micdoodle8/Galacticraft/commit/fed8e312eaf42d42f951ca446488fb0affda28ed)
 - PlayerAPI (https://github.com/micdoodle8/Galacticraft/commit/3c91efd395d0389f0e9934580505466061cc0da8)
 - AppliedEnergistics (https://github.com/micdoodle8/Galacticraft/commit/1672ddadc03bbf3d6b042049605671529e03394b)
 - RedstoneFlux (Previously COFHCore - https://github.com/micdoodle8/Galacticraft/commit/c6e110726c4dbb20e09287ce44fa06209a492ecf)
 - BOP (https://github.com/micdoodle8/Galacticraft/commit/c6e110726c4dbb20e09287ce44fa06209a492ecf)

**Please Note, I'm still getting used to Java so I'm hoping that I didn't too too many things incorrectly xD**

**PS Don't Merge Yet as this is still WIP and I'd like to make sure I didn't break anything in this**

**If Merged with JEI API Update, would Replace #2887**

### CODE REVIEW

**Comment by Romsik788** [comment]
Good work

**Comment by radfast** [comment]
hey @CDAGaming thanks for taking the trouble to make a Pull Request with a number of different things.  We certainly welcome help with the Galacticraft project from good coders.  If a new person - like you - joins the dev team, then the pace of GC updates can maybe increase, as micdoodle8 and I are often too busy with studies and work and other real life stuff.

As with all Pull Requests, I'm going to want to look at each element of this separately, so it would be best if you can make a separate pull request for each commit, please.

1.  The API changes, are you simply replacing files in the dependencies folder with an updated version of the other mod's API (+ _at in JEI's case), or are you updating Galacticraft code at the same time?

2.  Your PRs should be based off the latest code in 1.12 branch, so "origin/master merge" shouldn't be in your PRs...

3.  Some of your elements are workspace and gradle changes.  These types of changes are unlikely to be acceptable, unless you can explain precisely why they are necessary....   For example, micdoodle8 and I have decided to use the "Recommended" .2555 build of Forge to build against: is there a good reason why you are requesting to change to .2586?

**Comment by CDAGaming** [comment]
1. Yes, so far its just replacing with an Updated Version. I plan to continue working on this today by replacing any parts in Galacticrafts Code that need it.
2. I agree there, especially because of the one commit exclusion which can cause some Issues.
3. The .gitignore Changes just make Life Easier for others when using runClient and runServer to test Galacticraft. The Gradle Wrapper changes are not entirely necessary so that can be removed. As of MCP and Forge, I thought it would be good to keep both dependencies Up to Date to include any Improvements and fixes that come with them.

**Comment by radfast** [comment]
hmm

1.  In that case I think it's better you leave the API issues to me, as I am probably more familiar with GC's current codebase and the implications of any changes in third party APIs.  The way we use other APIs is not always too clear, with Java reflection etc.

3.  Please can you make a separate PR with only the ```.gitignore``` changes and then I can merge that one?

I do not want to change the Forge version.  I think Galacticraft is actually **more** widely compatible with other mods (including in a dev environment) if we don't use the bleeding edge Forge version in our workspace, because it's unlikely that every other mod will continually update to the bleeding edge.  The recommended .2555 seems a reasonable place to be - kind of like a base camp.  If we become aware of any issues with more recent Forge updates we can deal with that in future.

**Comment by radfast** [comment]
Please also see #3090, I would welcome:
(a) help with any issue listed here, unless I've self-assigned it
(b) testing of 1.12 version, please add any new issues to this list

**Comment by CDAGaming** [comment]
I'll Split this PR Up shortly. I do know of one issue ingame so far which I will also post in #3090

**Pull request closed without merging**
