### PR TITLE
Fix stairs in #3343

### PR DESCRIPTION
**Pull request by Romsik788**
I fixed only the stairs. Because I did not understand what needs to be corrected in Slabs and Walls.

### CODE REVIEW

**Comment by SteveKunG** [comment]
Crafting pattern should be like this, based on vanilla recipe.

**Comment by Romsik788** [comment]
@SteveKunG The stairs and walls have a pattern like vanilla recipe

**Comment by SteveKunG** [comment]
Yeah, they just add reverse recipes, vanilla already do that in the code.

**Comment by Romsik788** [comment]
hmm. Then why is the problem #3343 open if this is not problem?

**Pull request closed without merging**
