### PR TITLE
Add an option to disable small asteroids entirely

### PR DESCRIPTION
**Pull request by marcus8448**
A handful of server owners on the GC discord seem to still have lag problems with small asteroids, even after https://github.com/micdoodle8/Galacticraft/commit/579479ab4a64b0133177b552602c290c6a196cc3, so I made a config option to disable the asteroids entirely.

### CODE REVIEW

**Comment by baddiePRO** [comment]
Nice

**Comment by SebaSphere** [comment]
Yeah quite a bit of people have had trouble with that. The asteroids also do cause dips on some people's fps. 
image

**Comment by micdoodle8** [comment]
I'm not sure why I hadn't thought of this already. Thank you :)

**Comment by Agilazul** [comment]
HI, where i can desactive the asteroids in which config?

**Pull request merged**
