### PR TITLE
Italian Update

### PR DESCRIPTION
**Pull request by QuodQuaeris**

### CODE REVIEW

**Comment by radfast** [comment]
Thank you, so fast!

You might want to make "Gomma per la spazzola" something shorter, maybe that will not fit in the space in the GUI: see #1790 for a screenshot of the GUI.

**Comment by QuodQuaeris** [comment]
I'll do it now :)

**Comment by darthvader45** [comment]
Btw, gomma means rubber in Italian.  Might want to change it to Raggio di spazzola, which means Brush radius.

**Comment by radfast** [comment]
Any more additions to the Italian translation, please feel free to suggest them.  Best way is to directly edit the [lang](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftcore/lang/it_IT.lang) file and then make a Pull Request on Github.

For the brush, I think these translations were already changed to Pennello + Dimensione pennello, some time later in Jan 2016.

**Pull request merged**
