### PR TITLE
Issue template proposal

### PR DESCRIPTION
**Pull request by EzerArch**
This is a short version of the 'Guidelines for Contributing'. It will be used as template when a user clicks on "New issue".

Preview:
issue template preview

**Details:** https://github.com/blog/2111-issue-and-pull-request-templates

Feel free to propose changes, especially as to making it shorter. ;)

### CODE REVIEW

**Comment by radfast** [comment]
oh wow, I didn't know this was possible!

yeah we should definitely do this, but I want to simplify the language a bit

I suggest put this on hold for a few days, as especially right now while things are in BETA, we want **all** issues reported - and almost all the issues recently reported have been valid

**Comment by dj3520** [comment]
Oh my gosh. Good discovery.

**Comment by EzerArch** [comment]
*bump*

A "few" days has passed. Just bumping for "memory".

**Comment by radfast** [comment]
!https://img.buzzfeed.com/buzzfeed-static/static/enhanced/webdr06/2013/7/1/9/enhanced-buzz-orig-13765-1372685755-19.jpg?downsize=715:*&output-format=auto&output-quality=auto

**Comment by radfast** [comment]
Thanks @EzerArch 

I made a simplified version, please see what you think.

The main thing in recently opened issues is people are not even saying the Minecraft version (this was requested on the forum beta testing thread, but players now are not beta testers), and often people don't say if it's SSP or SMP which can be important.

**Comment by TheQuadShot** [comment]
Here's my 2 caps worth:


## Base information
* Minecraft version:
* Minecraft Forge version:
* Mod Pack: (if applicable)
* Mod List: (Please pastbin)
* Crash Report/Latest.log (Please pastbin)
* Screen Shots (if applicable, please imgur)

## Description
Please try to be as verbose/detailed as possible :-)

**Comment by radfast** [comment]
Thanks again @EzerArch and @TheQuadShot 

Looking at the newest issue report #2895, I'm happy with the template as it is now I think - it's not too heavy for people to fill in, and covers most types of issue which get reported.  All three of us can keep an eye on this and adapt as we need it.

Generally I don't want mod pack information, as the last thing I want to be doing is downloading all the modpacks which incorporate Galacticraft and troubleshooting their compatibility and config issues!

**Pull request closed without merging**
