### PR TITLE
Update JEI API to 4.5.0

### PR DESCRIPTION
**Pull request by SteveKunG**
- Fix deprecated methods/classes warning in dev workspace

~~Note : DO NOT Merge this, I missed understand some method, will fix soon.~~
Edit : Fixed

### CODE REVIEW

**Comment by radfast** [comment]
Thanks for this.  What will happen if players have installed an older version of JEI (before 4.5.0)?

**Comment by SteveKunG** [comment]
I'll test soon, due my HDD broken :(

**Comment by radfast** [comment]
Oh noes!  Sorry for your HDD.

Do you know the "freezer trick"? If a HDD has physically died, just clicking all the time (from head recalibration) you can sometimes get an extra 30 minutes life, enough to copy key data, by putting it in the freezer.

**Comment by dj3520** [comment]
Need a tester? I'm fine with personal beta builds.

**Comment by SteveKunG** [comment]
Test 1:

GC Build 114 with old JEI API
JEI Version : 4.5.0

Mod ID not show in the recipe tab.


Compare with my mod.

**Comment by radfast** [comment]
> JEI Handler will not registed in-game because of java.lang.NoSuchMethodError.

Ideally we don't want this problem ... and I don't like Galacticraft to have dependencies on a specific version of another mod, it makes problems for average players who create their own modpacks.  (Forge error message when the dependency version needs updating is unhelpful...)

**Comment by MJRLegends** [comment]
Using a older version of jei with this change made doesnt cause issues from what i can see as ive made the change in my addon and so far so good

**Comment by radfast** [comment]
Sorry for the time taken, I have now updated 1.11 branch to JEI 4.5.0.  (This will also smooth the update to JEI 4.8 in our new 1.12 branch.)

The problem I was concerned about - breaking JEI compatibility for any of our 1.11 players who are still using pre-4.5.0 versions of JEI - is fixed by https://github.com/micdoodle8/Galacticraft/commit/3dd14bbfb4b26eb6a672597ab5680c88e5f9d665.

**Comment by radfast** [comment]
Thanks to @SteveKunG for this PR

**Pull request merged**
