### PR TITLE
GalacrticraftMars - Italian Translation

### PR DESCRIPTION
**Pull request by QuodQuaeris**
This is the italian translation for Galacticraft Mars. Next week I will translate GalacticraftAsteroids and GalacrticraftMoon. :D

### CODE REVIEW

**Comment by radfast** [comment]
That's great.  Moon and Asteroids are short - you did the main one already.

This will make a big difference for Italian players I'm sure - especially younger kids who do not know English.

**Comment by QuodQuaeris** [comment]
I'm very glad you like it :) I will follow Galacticraft's updates and provide new italian translations :)
Thank you :D

**Comment by radfast** [comment]
We use @QuodQuaeris to notify translators of any major localisation updates, especially when I run an auto-update tool - example: https://github.com/micdoodle8/Galacticraft/commit/f5b7e1c0f03a97a9d771b7690f749f7484023990

**Comment by QuodQuaeris** [comment]
Ok :D

**Pull request merged**
