### PR TITLE
Updated to the latest forge

### PR DESCRIPTION
**Pull request by TheCricket**
the obj's seem to not work though, but I don't know why that would happen

### CODE REVIEW

**Comment by micdoodle8** [comment]
There seems to be some other things changed in the diff as well. Why is there a new constructor for MCDataOutputWrapper? Did you update the NEI API?

**Comment by TheCricket** [comment]
Nope, I forgot that my autoreformater was on. It just moved it

**Comment by micdoodle8** [comment]
Oh okay. Well I've committed the updated forge changes, I am actually using the recommended forge in my workspace but had forgotten to actually commit the changes. Thanks for reminding me.

**Comment by TheCricket** [comment]
No Problem :)

**Pull request closed without merging**
