### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by Adaptivity**
Translated "Entry Pod" like "Lander", should be ok, right? Not sure how translate *gui.message.astroMiner2.fail* though.

### CODE REVIEW

**Comment by radfast** [comment]
Should be fine, the Entry Pod is the lander for the Asteroids.

We plan to have a configurable "per player" maximum limit on Astro Miners because otherwise they can be overpowered.  For example, maximum 3 per player.  Then gui.message.astroMiner2.fail is the message the player will see if he tries to place Astro Miner number 4.

**Comment by radfast** [comment]
Thank you for the super-quick update, by the way :)

**Comment by Adaptivity** [comment]
You're welcome. "That would be one Astro Miner too many!" still sounds weird for me even in English. Maybe you can change it to something like: "You have reached Astro Miner's amount limit"? Or something else?

**Comment by radfast** [comment]
The "fail" messages in English are supposed to be a little bit jokey.  But you're right, I guess it's not clear what that means, so I'll think about an alternative.  I'm happy for you to translate this into Russian already in any way that seems idiomatic to you - it can be "You have reached Astro Miner's amount limit" if you want... !

**Pull request merged**
