### PR TITLE
Added some missing entries to language file

### PR DESCRIPTION
**Pull request by MJRLegends**
Noticed there was some missing entries in language when testing my addons language files, i have marked them with ##NEEDS TRANSLATE## tags as i only know english :D 

There are some more missing ones in the other language files but didnt have time to do all today

### CODE REVIEW

**Comment by Romsik788** [comment]
Why did you delete some necessary lines in ru_RU? Why did you replace some lines of Russian translation into English? And please if you do not know Russian then DO NOT EDIT Russian lines!

**Comment by MJRLegends** [comment]
Look at all the commits not just the first

**Comment by MJRLegends** [comment]
@Romsik788 But please dont worry i know what im doing when it comes to minecraft mods, nothing has been deleted overall in this pull request. the commits you see all add to only be added changes not removals.

**Comment by Romsik788** [comment]
Ok I understood

**Comment by ETStarLight** [comment]
Well……what had you done to zh_CN.lang？

**Comment by radfast** [comment]
@MJRLegends  seems like this is causing controversy!!

I think it's better if I update the automated tool I made which compares all .lang files to the .en_US which we work on, and adds missing lines to all.  Best to do all, not some, I think :)

You happy if I close this PR?

**Comment by MJRLegends** [comment]
Yep no problem

**Pull request closed without merging**
