### PR TITLE
Update zh_CN.lang for Achievements 3 months ago

### PR DESCRIPTION
**Pull request by ETStareak**
Yeah I have finished it,and found two mistakes in en_US. lang. 
1.Lost a "n" before 'oxygen';
2. incorrect description of the achievement about advanced wafer, the description before IS about the machine?

### CODE REVIEW

**Comment by radfast** [comment]
Nice, you are the first.  Thank you for the en_US corrections.  I'm not sure about the "browned wafer" comment, I feel that should come out?

**Comment by ETStareak** [comment]
Well,it was a mistake.

**Comment by radfast** [comment]
The Advanced Wafer in game is supposed to be a golden colour like these pictures of silicon chip wafers.  It is not possible to draw this level of detail on a 16x16 icon, and it's difficult to show a golden shine.  That's why we went with the brown look.  But you should write "Golden Wafer" in the en_US.

**Comment by ETStareak** [comment]
@radfast  Okay I have finished it……But why don't you edit it yourself after merge the Pull Request?

**Comment by radfast** [comment]
Thank you, I can edit, but I want to make sure you are happy :)

**Comment by ETStareak** [comment]
Please merge it first……～(￣▽￣～)(～￣▽￣)～

**Comment by ETStareak** [comment]
@radfast  emmmmm, why isn't it merged?It has been one month……

**Comment by ETStareak** [comment]
@radfast hey What's wrong?Why haven't it been merged?!

**Comment by EzerArch** [comment]
Hmm, let's see what I can do. BRB.

**Comment by EzerArch** [comment]
> hey What's wrong?Why haven't it been merged?!

Weird, @radfast has been here a few days ago and missed your PR. I'll try to contact him.

But........ I recommend you renaming the PR back.

**Comment by EzerArch** [comment]
Thank you. I've sent @radfast a message. :)

**Comment by EzerArch** [comment]
*bump* (so for @radfast or @micdoodle8 not to miss it)

**Comment by micdoodle8** [comment]
Apologies for the delay, thank you!

**Pull request merged**
