### PR TITLE
Update nl_NL.lang

### PR DESCRIPTION
**Pull request by HellThunder**

### CODE REVIEW

**Comment by HellThunder** [comment]
I Deleted by accident this sentence i dont know it is very bad

gui.rocket.updown.name=Turn up-down ##NEEDS TRANSLATE##

**Comment by radfast** [comment]
It's OK, I'll fix it.  Thank you for the rest.

**Comment by radfast** [comment]
See:
https://github.com/micdoodle8/Galacticraft/commit/b55ea98534f048215d1751a3759a6e146b322c9e

I hope it's OK ... Google translate :)

**Comment by HellThunder** [comment]
Yes I use alot Of GOOGLE TRANSLATE but i make it so the translate is good (i am Dutch)

**Pull request merged**
