### PR TITLE
[Request] Allow other planet can have rainfall

### PR DESCRIPTION
**Pull request by SteveKunG**

### CODE REVIEW

**Comment by BlesseNtumble** [comment]
for 1.7.10 and 1.8.9 pls.

**Comment by EzerArch** [comment]
Since we have addons with snowy/dusty dimensions: Is it possible to expand it to snowfall?

**Comment by SteveKunG** [comment]
Its work with snowfalls too.
@BlesseNtumble for 1.7 might be soon.

**Comment by micdoodle8** [comment]
I made a few changes.

- Deprecated `canRainOrSnow` method, replaced by this new method
- Changed method name in your commit from `canDisableRain` to `shouldDisablePrecipitation`

**Pull request closed without merging**
