### PR TITLE
Better core advancements

### PR DESCRIPTION
**Pull request by marcus8448**
Advancements should now show you how to progress in Galacticraft.
https://imgur.com/a/9Rr64G1

### CODE REVIEW

**Comment by radfast** [comment]
hey @marcus8448 - in at least some Forge versions (2555), `CriteriaTriggers.register()` is a private method.

**Comment by radfast** [comment]
Fixed in https://github.com/micdoodle8/Galacticraft/commit/d2fe15094d7b9d9c8c6a19ddac67a2284bf97e2c - I don't know which exact Forge versions this is needed for, but not taking any chances.   We aim to be compatible with **all** recommended Forge 1.12.2 versions not only the latest (and likewise we aim for compatibility with older versions of other major mods)   The reason for this is so that even people with old modpacks can safely update Galacticraft in the pack without breaking compatibility.

(Obviously the exception to this is Galacticraft add-on mods like ExtraPlanets, those will always need to be updated to match the current Galacticraft version because we have to update the API and core sometimes to fix issues or make improvements.)

**Comment by marcus8448** [comment]
Forge version `14.23.1.2598` was when `CriteriaTriggers#register` was exposed (MinecraftForge/MinecraftForge#4634). Instead of reflection, you could just add a line to Mic Core's AT.
`public net.minecraft.advancements.CriteriaTriggers func_192118_a(Lnet/minecraft/advancements/ICriterionTrigger;)Lnet/minecraft/advancements/ICriterionTrigger; # register`

**Comment by radfast** [comment]
I've coded it now using reflection.  There is no performance impact because it will call this only once when the game starts, anyhow using reflection on known classes is fairly efficient (it's Class.forName() searches which are inefficient.)

Changing the AT would (I think) require everyone developing Galacticraft to rebuild their dev environment, so I tend to try not to do that where reflection can solve the problem.

The very long standing policy of the Galacticraft team is to try not to have restrictive minimum version requirements for Forge or other mods, it's almost a point of pride for me.  We do not have statistics on who uses Galacticraft with which Forge versions, but anecdotally I think there are some players who download Forge only once per Minecraft version, and never update it.  (Of course sometimes a Forge update is forced if another mod has a minimum Forge version requirement.)

**Pull request merged**
