### PR TITLE
[1.8.9] Use maven repos instead of dependencies/ folder

### PR DESCRIPTION
**Pull request by marcus8448**
Removes **MFR compat & Mekanism compat** _(There are no compiled versions of these mods for 1.8.9/1.8 released)._
The version of _codechicken-lib_ is for **1.9.4**, but it has the _same functionality._

### CODE REVIEW

**Comment by micdoodle8** [comment]
Thank you :)

**Comment by micdoodle8** [comment]
Hey, are you using a local gradle distribution, or the one packaged with forge? I'm getting an error with compileOnly

If it's easier, I'm on the [discord](https://discord.gg/N4ndFkr) server.

**Comment by marcus8448** [comment]
Wow... I messed up. I used gradle 4.9 instead of 2.7. In that case... Feel free to revert the commit, and I will try to see if I can get things sorted out.

**Comment by MJRLegends** [comment]
Just change the complieOnly to compile

**Comment by marcus8448** [comment]
Yeah, I tried that before, but it also causes forge to run the mods in the dev environment.

**Comment by MJRLegends** [comment]
Ahh yea my mistake, i believe 

> provided  

is what you want

**Comment by MJRLegends** [comment]
Also while we on the topic of mavens, @micdoodle8 please could you put GC on to a maven. :P

**Comment by SteveKunG** [comment]
So, I fixed it (1.12.2). Only RedstoneFlux require full mod in dev.
https://github.com/SteveKunG/MorePlanets/blob/1.12.2/build.gradle#L72-L100

**Comment by marcus8448** [comment]
> Ahh yea my mistake, i believe
> 
> > provided
> 
> is what you want.
> 
> > the 'provided' configuration is for optional dependencies that exist at compile-time but might not at runtime.
lol, yeah. Now I'm trying to remember why I was using `compileOnly`

**Comment by marcus8448** [comment]
@MJRLegends - Since GC isn't on a maven, you can use Jenkins as an ivy repo:
```groovy
String GCBuild = "243"
String GCVersion = "1.12.2-4.0.2.${GCBuild}"

repositories {
    ivy {
        url "https://ci.micdoodle8.com/job/"
        layout 'pattern', {
            artifact "[organization]/${GCBuild}/artifact/Forge/build/libs/[module]-[revision].jar"
        }
        metadataSources { 
            artifact()
        }
    }
}

dependencies {
    compile "Galacticraft-1.12-dev:GalacticraftCore-Dev:${GCVersion}"
    compile "Galacticraft-1.12-dev:Galacticraft-API:${GCVersion}"
    compile "Galacticraft-1.12-dev:Galacticraft-Planets-Dev:${GCVersion}"
    compile "Galacticraft-1.12-dev:MicdoodleCore-Dev:${GCVersion}"
}
```

**Pull request merged**
