### PR TITLE
Add config option to make moon breatheable

### PR DESCRIPTION
**Pull request by ROMVoid95**
I've seen this type of config option request many times so wanted to give this a shot at getting added.

### CODE REVIEW

**Comment by ROMVoid95** [comment]
Should have also noted that i did test this and did not find any issues.

**Comment by TheQuadShot** [comment]
Sorry if I'm out of line here, but I've never seen anyone request this. If it were up to me, I would deny it on the principle of it. You can't breath on the moon, and if it's done for the moon, then why not planet x/ or dim __

**Comment by ROMVoid95** [comment]
> Sorry if I'm out of line here, but I've never seen anyone request this. If it were up to me, I would deny it on the principle of it. You can't breath on the moon, and if it's done for the moon, then why not planet x/ or dim _x_

i mean maybe you haven't. I wouldn't call this an option that everyone is screaming for, but one where in normal multiplayer chat players and owners have thrown out the "hey, you know what would make *showcase world/spawn world/* easier". without having to grab another mod for it. If it doesn't get accepted then that's that, if it does then you don't have to enable it, or even look at the config option. And why the moon? it's literally the only dimension/planet that has been mentioned the 20 or so times just myself have heard.

**Comment by EzerArch** [comment]
> Sorry if I'm out of line here, but I've never seen anyone request this

@TheQuadShot this is really old. Probably when Galacticraft was just the moon. But never heard of it ever since. I agree that such option would remove a very important feature of Galacticraft and we'd need to change other features that depend on it (e.g. Life support system, flight check list etc).

**Comment by radfast** [comment]
>  I've seen this type of config option request many times so wanted

Links please?  You are asking us to spend valuable coding time to disable a core mechanic of Galacticraft.  I will need to see a good persuasive reason for that, or it's not going to happen.

Generally, I don't like adding config options for 1 person's special request or modpack, because we already have a lot of config options, it's already confusing for new players and people who don't like to research the details.  Each new config adds to the complexity for everyone else.

**Comment by ROMVoid95** [comment]
My Lord I don't know why that didn't send with commit. It's missing a change to WorldProviderMoon class. I'm out of town so I'm on mobile. If this isn't something that would be accepted I'll just close this.

**Comment by ROMVoid95** [comment]
Btw, congrats on 10 million downloads!!

**Comment by ROMVoid95** [comment]
went ahead and just added the missing method for the hell of it, 
> Needs more (maybe not much more?) to code it.
it just needed 1 method in the worldprovider to make possible. anyway if it's still open in a day or two ill close it so its not taking up space in the pull request list. thanks for looking anyway

**Pull request closed without merging**
