### PR TITLE
Update EntityTieredRocket.java & RenderPlayerGC.java

### PR DESCRIPTION
**Pull request by gug2**
Edit any files

### CODE REVIEW

**Comment by EzerArch** [comment]
Just to advance a bit, what specifically are you aiming to change/fix here?

**Comment by gug2** [comment]
@EzerArch  I fixed the bugs  that was displayed in my workspace

**Comment by micdoodle8** [comment]
Changes look good, but I'm going to need some more information please. 

What bugs did you fix? Specifically, why did you change `targetDim` to the rocket's current world object?

**Comment by gug2** [comment]
_targetDim_ was not visible in EntityTieredRocket.java in my workspace

**Pull request closed without merging**
