### PR TITLE
Disabled switching to third-person if Vivecraft is installed (needs testing)

### PR DESCRIPTION
**Pull request by Brycey92**
Should provide a solution for #2405.

### CODE REVIEW

**Comment by radfast** [comment]
Hey @Brycey92 
Thanks for this.  We will also need to disable the zoom in the same piece of code - it's probably the zoom, not the switch to third person view, which is the biggest cause of the problem here.

And for future compatibility with other VR - maybe even after we've stopped developing GC 1.7.10 - I think it's best to use a client-side config setting.

Do you want to make these changes and make a fresh PR?  If I don't hear from you today, I will make the changes and give you credit in the commit title.

By the way, please always update your fork fully **before** starting a PR, otherwise your PR includes extra commits like 440c441 which makes the merge messier.

**Comment by Brycey92** [comment]
I can change this into a config setting, and I'll look for the zoom code. Also, what do you mean by "update your fork fully before starting a PR?" I hadn't started this PR before making that merge commit.

**Comment by radfast** [comment]
I mean, in general best practice is to do it in a way that your PR only contains 1 commit, not 2 commits like here, but NVM.  All help with GC is greatly appreciated :)

You will make a fresh PR with the new code?  Then I can close this.

**Comment by Brycey92** [comment]
Sure, I'll make the new PR now.

**Pull request closed without merging**
