### PR TITLE
Added basic atmospheric pressure 

### PR DESCRIPTION
**Pull request by katzenpapst**
See also the pull request in Galacticraft-API. Based on this change, I made the gas liquefier dependant on the atmospheric pressure. I also adjusted the pressure on Mars to be 2% of Earth's. This is technically too high, but even with this value the gas generation is VERY slow. And, in the end, this is just a suggestion.

See also: http://forum.micdoodle8.com/index.php?threads/pressure.3972/

### CODE REVIEW

**Comment by radfast** [comment]
Hmm.  I just read Andy Weir's *The Martian* so I get where you're coming from with this.

I'm not sure the Gas Liquefier needs to operate so slowly at low pressure, maybe it does not need 1 atmosphere of pressure to operate at full efficiency.  You can also imagine there could be some type of powered compressor system built in to the Atmospheric Valve.

I'm concerned that if in future we add gas giants, they will have an extremely high atmospheric pressure (at the surface...), even worse for Venus.

If we add this there therefore needs to be an interaction with safety + life support equipment that the player needs, e.g. high pressure suit.

**Comment by BlesseNtumble** [comment]
WorldProviderSpace -> IGalacticraftWorldProvider

**Comment by katzenpapst** [comment]
I was thinking about adding an "IItemPressurized", extending "IItemThermal" and adding a "getPressureProtection" method. As I wrote in the forum thread, I'm not sure whenever it should be necessary to protect against low pressure. Maybe only on hardcore difficulty? And then the suit should be craftable from Overworld materials, for obvious reasons.

Regarding other parts: mhh not sure. While working on my own mod I've come across some things which might be worth refactoring, but dunno. Suggest something at me :D 

@BlesseNtumble Haven't seen this interface before. Is it new?

**Comment by C1ffisme** [comment]
Coincidentally, I'm doing a chemistry lesson about gases and pressure. Isn't that just hilarious?

I would like to finally have a pressure suit so that I can look like an actual spaceman.

(Perhaps to save the amount of armor you have to put on, we should use the thermal armor slots for the pressure suit, and putting the two together would keep you warm and pressurized at the same time.)

**Comment by katzenpapst** [comment]
Okay, I added the IItemPressurized to the PU (see also the one for GC API). Haven't added any items yet, but it should work. Also, sorry for useless whitespace changes, Eclipse was just being an idiot ._.

**Comment by EzerArch** [comment]
Wouldn't ```_AtmosphericPressure``` render ```_SoundVolReductionAmount``` redundant? I think, with some "artistic license", sound volume should be directly proportional to air pressure.

I was using ```_SoundVolReductionAmount``` as pressure on the wiki already (see [Planets doc page](http://wiki.micdoodle8.com/wiki/Template:Planet/doc)) but I would really prefer something more descriptive. :)

**Comment by katzenpapst** [comment]
Oh hm, I haven't thought about that. So 1/pressure would be sound reduction? 

Also, I'm still not sure what to do about low pressure...

**Comment by EzerArch** [comment]
@katzenpapst:

> So 1/pressure would be sound reduction? 

No. That would be ```volume * pressure```, because pressure ranges from 0.0 (no sound), 1.00 (normal) and above. ```_SoundVolReductionAmount``` is kinda backwards (hence the ^(-1)): the more ```_SoundVolReductionAmount```, the less you can hear.

The problem I've just noticed is you might end up getting sound volume too close to zero with air pressure as low as 0.0063. On a second thought, I'd keep sound volume not directly linked to air pressure. 

More on the subject: http://forum.micdoodle8.com/index.php?threads/pressure.3972/#post-40575

**Comment by katzenpapst** [comment]
So, I tried to add a pressure gauge to the GUI recently. While rendering the thing isn't much of a problem, passing all the values around like it is done for the thermal level seems to be quite a task... The question is, should I even continue?

**Comment by BlesseNtumble** [comment]
I think that the pressure line is better to make vertical.

**Comment by micdoodle8** [comment]
Closing for now, it's possible that this will be re-visited at a later date.

**Pull request closed without merging**
