### PR TITLE
Warnings cleanup

### PR DESCRIPTION
**Pull request by SteveKunG**
Just warnings cleanup. Not sure this will improve a little performance.

### CODE REVIEW

**Comment by radfast** [comment]
hi @SteveKunG  this is a good idea

But ... I find such a large commit difficult to read and check (and maybe it will make merging branches very difficult).

And at this time I do not want to remove the `//` commented out lines of old code.  Sometimes that's been done very quickly on Minecraft version updating to overcome compile errors and it indicates something that is still "To do".  I would need to review each one separately to be sure ...

I have implemented the first two of your things here in the linked commits.  Please can you rebase this PR and make a fresh commit for everything else that is needed?

Do we still need to update ```gitignore```?   I could not figure it out because you changed it then restored it!  I am happy to change ```gitignore``` as you need.

**Comment by SteveKunG** [comment]
Thank you, then I will close this and split it up to make it easy check.

For `gitignore` I don't want to include all gradle stuff when I create pull request, could you add it by default?

**Comment by radfast** [comment]
See https://github.com/micdoodle8/Galacticraft/commit/d73779eb25c63c4291eabcb3f6b478c739d13ef3 for gitignore

I hope it's OK for you?    /run/ is already in the .gitignore

We have to comment out `#parts` because there are folders in the sources with that name - really I would like to comment out all the Python stuff, you shouldn't need to mix Python code in with your Java workspace.

**Comment by SteveKunG** [comment]
Yes, I've update latest .gitignore file.

**Comment by radfast** [comment]
@SteveKunG  some of these things you can fix by changing your IDE warnings settings.

For example:   Incomplete `switch () ... case` definitions or missing `default` case is OK, it's not an error.

Also I think method parameters like `List<BlockPos>` shouldn't need to be specified with their types - I think in Java at compile time it is always `List<?>` even when your code gives an actual type.  I'm not sure about this though.  If you know of any documentation / StackOverflow for this, please give me a linkl?

**Comment by SteveKunG** [comment]
Very hard to find it on website because there is no Thai article about this.
https://stackoverflow.com/questions/6231973/difference-between-list-list-listt-liste-and-listobject

**Pull request closed without merging**
